# Reusable GitHub Actions Workflow: Deploy .NET App to Azure App Service
#
# Copy this file into your project as .github/workflows/deploy-app.yml
# and update the env variables below.
#
# Prerequisites:
# 1. GitHub OIDC federation configured (see docs/new-project-guide.md)
# 2. App Service Web App or Function App created via Bicep
#
# Required GitHub secrets:
#   AZURE_CLIENT_ID       - App registration client ID for OIDC
#   AZURE_TENANT_ID       - Azure AD tenant ID
#   AZURE_SUBSCRIPTION_ID - Azure subscription ID

name: Deploy to App Service

on:
  push:
    branches: [main]
    paths-ignore: ['infra/**', 'docs/**', '*.md']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  # --- UPDATE THESE FOR YOUR PROJECT ---
  AZURE_WEBAPP_NAME: 'func-yourproject'
  DOTNET_VERSION: '8.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: dotnet publish -c Release -o ./publish

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./publish
